# Generated by Django 5.1.6 on 2025-03-02 06:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guionhistorial',
            name='guion',
        ),
        migrations.RemoveField(
            model_name='guionhistorial',
            name='pose_actores',
        ),
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('kwh', models.FloatField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.user')),
            ],
        ),
        migrations.DeleteModel(
            name='Guion',
        ),
        migrations.DeleteModel(
            name='GuionHistorial',
        ),
        migrations.DeleteModel(
            name='Pose',
        ),
    ]
