# Generated by Django 5.1.6 on 2025-03-02 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_factura_valor'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='año',
            field=models.IntegerField(default=2025),
        ),
        migrations.AddField(
            model_name='factura',
            name='mes',
            field=models.IntegerField(default=1),
        ),
    ]
