# Generated by Django 5.1.6 on 2025-03-02 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_factura_año_factura_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.user'),
        ),
    ]
